### ISSUE TITLE
Prompt user for Camel configuration path

### ISSUE THREAD

**Issue by kcbabo** [fabric8io/data-mapper#130]
Let's be a bit more flexible with how we handle Camel configuration.  Right now, we assume that the user is using Spring configuration and that the config is always in the same place (META-INF/spring/camel-context.xml).  I would like to let the user choose the location of their config and also open up the possibility that the config can be a Spring application context (what we use today) or an OSGi blueprint definition (new).  I should be able to hide the difference between the two inside the core tooling config library, so all the UI needs to do is allow the user to select a path and then pass that path down to the CamelConfigBuilder.

There are two points where the user should be prompted for the Camel configuration location:
1) In the new wizard, we need to add a mandatory input that allows the user to choose their configuration.  This should be a resource browser and it should default to a filter of "*.xml" within the META-INF and OSGI-INF directories of src/main/resources.
2) When the user opens up an existing mapping file.  Same browser as described above.

Some background:
https://groups.google.com/forum/#!topic/data-mapper/dqi-v4pZxic

**Comment by bfitzpat** [comment]
Ok... So I'm working on this now and have a few things working so far...

First, the wizard no longer lets you "finish" if there are any fields with errors. There were some issues with the wizard page validator I worked around using some data binding support to prevent this. The upshot is that the errors and warnings that appear as decorators now also appear at the top as errors and warnings. :) 

Second, I added a "Camel File path" field with a browse button. The browse button right now opens a dialog that browses for all "*.xml" files right now, but I think I can filter that down further. It only grabs the list of xml files that are on the project classpath for now.

Third, I added some checks:
1) If the user types a Dozer File path name that already exists, they see a warning that says the file already exists and the Finish button is active (if there are no other issues). If they click Finish, they are asked if they want to overwrite the file. 
2) Since we allow the user selecting any xml file at the moment for the Camel File, it verifies that the CamelConfigBuilder can load the file. Right now it can't seem to load a Blueprint file and shows it as invalid - but when support is under the covers it should work fine. I am assuming that a) the camel file has to exist and b) it has to be readable. (To test the Blueprint functionality I grabbed (apache-camel-2.14.1\examples\camel-example-twitter-websocket-blueprint) and tried to open the OSGI-INF/blueprint/camel-twitter.xml file.)

Here's an image of what it looks like with the new field, but otherwise it looks the same pretty much.
![data-mapper-dmwiz-camelpath](https://cloud.githubusercontent.com/assets/530878/6179429/6e1cda80-b2d6-11e4-81fb-a8991ff1fb08.png)

**Comment by jpav** [comment]
> On Feb 12, 2015, at 5:52 PM, Brian Fitzpatrick <notifications@github.com> wrote:
> 
> Ok... So I'm working on this now and have a few things working so far...
> 
> First, the wizard no longer lets you "finish" if there are any fields with errors. There were some issues with the wizard page validator I worked around using some data binding support to prevent this.
> 

AFAIK, the wizard already didn't enable the finish button unless there were no errors. Was there a hole in that?

> The upshot is that the errors and warnings that appear as decorators now also appear at the top as errors and warnings. :)
> 

I just removed those not too long ago based on feedback from Keith. I think the concern was the errors are too much in the user's face with the messages.

**Comment by bfitzpat** [comment]
There was a hole in the validation. Once I added another textual field with a validator (i.e. the camel path), if you cleared both fields, then typed into one or the other a couple of characters I could enable the Finish button. 

We can clear the errors/warnings from the get-go and offer reasonable defaults I think, but displaying them in the top of the wizard page is a pretty standard Eclipse practice. If the Finish button isn't enabled, I'd rather know the "why" more in my face. But we can chat further about this...

**Comment by jpav** [comment]
> On Feb 13, 2015, at 8:00 AM, Brian Fitzpatrick <notifications@github.com> wrote:
> 
> There was a hole in the validation. Once I added another textual field with a validator (i.e. the camel path), if you cleared both fields, then typed into one or the other a couple of characters I could enable the Finish button.
> 
> We can clear the errors/warnings from the get-go and offer reasonable defaults I think, but displaying them in the top of the wizard page is a pretty standard Eclipse practice. If the Finish button isn't enabled, I'd rather know the "why" more in my face. But we can chat further about this...
> 

I don't disagree, just saying that's how things were to begin with, so wanted to make sure everyone is good with going full circle on this. 😉

**Comment by bfitzpat** [comment]
I'm open to the debate. :) The benefit for me was the wizard page support for data binding-enabled controls. Not having to roll our own page validation logic is a huge plus.

**Comment by bfitzpat** [comment]
Ok I have my changes merged with the latest updates from jpav. Here's a PR to try. 

https://github.com/fabric8io/data-mapper/pull/134

Right now the mappings list at the top doesn't reset when the source/target models change, but jpav is addressing that with some other cross-platform issues I discovered on Windows vs. Mac.

**Comment by kcbabo** [comment]
pushed
